artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Sail2304/datasets/raw/refs/heads/main/LoanTap.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/LoanTap.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/LoanTap.csv
  ohencoder_path: artifacts/data_transformation/ohencoder.joblib
  le_grade_path: artifacts/data_transformation/le_grade.joblib
  le_subgrade_path: artifacts/data_transformation/le_subgrade.joblib
  le_emp_length_path: artifacts/data_transformation/le_emp_length.joblib


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  model_score: artifacts/model_trainer/model_score.txt
  scaler_path: scaler.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  scaler_path: artifacts/model_trainer/scaler.joblib
  ohencoder_path: artifacts/data_transformation/ohencoder.joblib
  le_grade_path: artifacts/data_transformation/le_grade.joblib
  le_subgrade_path: artifacts/data_transformation/le_subgrade.joblib
  le_emp_length_path: artifacts/data_transformation/le_emp_length.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: https://dagshub.com/Sail2304/LoanTap.mlflow

prediction_config:
  model_path: artifacts/model_trainer/model.joblib
  scaler_path: artifacts/model_trainer/scaler.joblib
  ohencoder_path: artifacts/data_transformation/ohencoder.joblib
  le_grade_path: artifacts/data_transformation/le_grade.joblib
  le_subgrade_path: artifacts/data_transformation/le_subgrade.joblib
  le_emp_length_path: artifacts/data_transformation/le_emp_length.joblib
